dataset:
    img_size: 32
    channels_img: 3
    num_classes: 10

# Nets: 
# Generator: DCGAN_Generator, WGAN_Generator, WGAN-GP_Generator
# Discriminator: DCGAN_Discriminator, WGAN_Discriminator, WGAN-GP_Discriminator
nets:
    generator: DCGAN_4x4_Generator
    discriminator: DCGAN_Discriminator
    disc_features: 16
    gen_features: 16
    latent_dim: 128
    embedding_dim: 16

training:
    batch_size: 128
    test_batch_size: 1000
    test_every: 10
    save_every: 50
    epochs: 1000
    gen_lr: 0.002
    disc_lr: 0.0002
    gamma: 0.5
    cuda: True # disable cuda if needed
    seed: 0
    disc_iterations: 1
    weight_clip: 0.0  #WGAN
    lambda_gp: 0  #WGAN-GP

    # Losses: BCELoss, ExpSigmaLoss, WassersteinLoss
    gen_loss: BCELoss
    disc_loss: BCELoss
