dataset:
    img_size: 32
    channels_img: 3
    num_classes: 10

nets:
    # Generator: DCGAN_Generator, DCGAN_4x4_Generator, DCGAN_4x4_Generator_Conv
    generator_model: DCGAN_Generator
    # Discriminator: DCGAN_Discriminator, DCGAN_Discriminator_FC,  WGAN_Discriminator, WGAN_Spectral_Discriminator,
    discriminator_model: DCGAN_Discriminator
    disc_features: 16
    gen_features: 16
    latent_dim: 128
    embedding_dim: 16
    # Normalizer: BatchNorm2d, LayerNorm, InstanceNorm2d; use "disc_normalizers: []" for no normalizer
    disc_normalizers:
        - BatchNorm2d
    gen_normalizers:
        - BatchNorm2d

training:
    batch_size: 128
    test_batch_size: 1000
    test_every: 10
    save_every: 50
    epochs: 1000
    gen_lr: 0.001
    disc_lr: 0.0001
    cuda: True # disable cuda if needed
    seed: 0
    disc_iterations: 1
    weight_clip: 0.0  #WGAN
    lambda_gp: 0  #WGAN-GP(gradient penalty)

    # Losses: BCELoss, ExpSigmaLoss, WassersteinLoss, FeatureMatchingLoss
    gen_loss: BCELoss
    disc_loss: BCELoss
