dataset:
    img_size: 32
    channels_img: 3
    num_classes: 10

# Nets: 
# Generator: Generator, DCGAN_4x4_Generator
# Discriminator: DCGAN_Discriminator, WGAN_Discriminator, WGAN-GP_Discriminator
nets:
    generator_model: Generator
    discriminator_model: WGAN_Discriminator
    disc_features: 16
    gen_features: 16
    latent_dim: 100
    embedding_dim: 16

training:
    batch_size: 64
    test_batch_size: 1000
    test_every: 10
    save_every: 50
    epochs: 1000
    gen_lr: 0.0004  
    disc_lr: 0.0004  
    gamma: 0.5
    cuda: True # disable cuda if needed
    seed: 0
    disc_iterations: 5
    weight_clip: 0.01  
    lambda_gp: 0  

    # Losses: BCELoss, ExpSigmaLoss, WassersteinLoss
    gen_loss: WassersteinLoss
    disc_loss: WassersteinLoss
