dataset:
    img_size: 32
    channels_img: 3
    num_classes: 10

nets:
    generator_model: DCGAN_Generator
    discriminator_model: WGAN_Spectral_Discriminator
    disc_features: 64
    gen_features: 64
    latent_dim: 128
    embedding_dim: 128
    disc_normalizers:
        - InstanceNorm2d
    gen_normalizers:
        - BatchNorm2d

training:
    batch_size: 64
    test_batch_size: 1000
    test_every: 10
    save_every: 50
    epochs: 1000
    gen_lr: 0.00002
    disc_lr: 0.00003
    cuda: True
    seed: 0
    disc_iterations: 5
    weight_clip: 0.0
    lambda_gp: 10
    gen_loss: WassersteinLoss
    disc_loss: WassersteinLoss
