dataset:
    img_size: 32
    channels_img: 3
    num_classes: 10

nets:
    generator_model: DCGAN_Generator
    discriminator_model: WGAN_Discriminator
    disc_features: 16
    gen_features: 16
    latent_dim: 100
    embedding_dim: 16
    disc_batchnorm: True
    disc_layernorm: False
    disc_instancenorm: False
    gen_batchnorm: True

training:
    batch_size: 64
    test_batch_size: 1000
    test_every: 10
    save_every: 50
    epochs: 1000
    gen_lr: 0.0004
    disc_lr: 0.0004
    gamma: 0.5
    cuda: True
    seed: 0
    disc_iterations: 5
    weight_clip: 0.01
    lambda_gp: 0
    gen_loss: WassersteinLoss
    disc_loss: WassersteinLoss
